name: Test
on:
  push:
jobs:
  Test:
    name: Test
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: |
          dist_package_tool
